### ISSUE TITLE
After not receiving packets for 9 seconds, BFD will never come up again

### ISSUE THREAD

**Issue by craig** [dyninc/OpenBFDD#13]
First of all, thanks for the good work, I really like OpenBFDD and we're currently using it on several servers.

Here is my setup:
- MX104 Router, JunOS 13.3R6.5, IP x.y.120.200
- Debian 7 with openbfdd-0.5.3, IP x.y.120.143

Juniper Config:
set routing-options static route x.y.121.20/32 next-hop x.y.120.143
set routing-options static route x.y.121.20/32 bfd-liveness-detection version automatic
set routing-options static route x.y.121.20/32 bfd-liveness-detection minimum-interval 300
set routing-options static route x.y.121.20/32 bfd-liveness-detection multiplier 3

Debian Config:
/usr/local/bin/bfdd-beacon --listen=:: --listen=0.0.0.0 --control=127.0.0.1:957
/usr/local/bin/bfdd-control session new set multi 3
/usr/local/bin/bfdd-control session new set mintx 300 ms
/usr/local/bin/bfdd-control session new set minrx 300 ms
/usr/local/bin/bfdd-control allow x.y.120.200

triggering the problem:
Wait a few seconds until the session is established.
on the Debian box, run: "iptables -I INPUT -p udp --dport 3784 -j DROP"
session is down after ~900ms on the juniper, checked with "show bfd session"
wait >9 seconds (very important!)
on the Debian box, run "iptables -F INPUT" (or restart your firewall, if you have one)

Afterwards, the openbfdd Daemon on the client will *never again* send any (!) packet out.
Restarting the Daemon does not help - the session will not come up anymore. My theory is that OpenBFDD receives the down packets from the Juniper box and never tries to INIT again, if it did not have an active session <~9 seconds ago. Weird!
This is a serious problem if you unplug a cable for more than about 9 seconds or mess up your firewall rules - BFD is down and you cannot fix it on the OpenBFDD side!
If the waiting time between dropping the packets in the firewall and allowing them again is smaller than about 9 seconds, OpenBFDD will send out an Init packet even after receiving several down packets.

You can fix it on the Juniper box by deactivating and activating BFD:
deactivate routing-options static route x.y.121.20/32 bfd-liveness-detection
commit
activate routing-options static route x.y.121.20/32 bfd-liveness-detection   
commit

This behaviour puzzles me and needs to be fixed IMHO, otherwise using BFD introduces a severe problem.

**Comment by idl0r** [comment]
Confirmed. I ran into the same issue.

**Comment by joker0x** [comment]
use 'connect local ip remote ip'  
juniper need active bfd configuration on both sides

**Comment by craig** [comment]
Whoa, you're my hero! Thank you so much, that solved it, wow! :) :+1: :100:
